Repository Mesh-DAO/rentskins_frontend, pull requests merged in 2023-07, with the labels that each got.

#56 [ Ítalo Araújo ] Renderizando as skins do inventario do user
  package.json
  src/app/api/get_inventory/route.ts
  src/app/detalhes/[id]/page.tsx
  src/app/inventario/[id]/page.tsx
  src/components/CheckBox/index.tsx
  src/components/Checked/index.tsx
  src/components/InputRadio/index.tsx
  src/components/Inventory/CardSkin/CardSkinContent.tsx
  src/components/Inventory/CardSkin/CardSkinImage.tsx
  src/components/Inventory/CardSkin/CardSkinRoot.tsx
  src/components/Inventory/CardSkin/index.tsx
  src/components/Inventory/CardSkinInventory copy.tsx
  src/components/Inventory/CardSkinInventory.tsx
  src/components/Inventory/LadoEsquerdo.tsx
  src/components/Inventory/Meio.tsx
  src/components/Modal/ModalAddSkin/CardSkinModal.tsx
  src/components/Modal/ModalAddSkin/InfoSkinModal.tsx
  src/components/Modal/ModalAddSkin/index.tsx
  src/components/Shared/Header/BottomHeader.tsx
  src/components/Shared/Header/TopHeader.tsx
  src/components/Skins/AllSkins/index.tsx
  src/services/Invetory.ts
  src/services/SkinService.ts
  src/stores/filters.store.ts
  src/stores/interfaces/filters.store.ts
  yarn.lock
Labels: Code Review

#61 [ Tiago Braga ] Forms - Refatoração do Componente
  package.json
  src/app/pagamento/recarregar/[method]/page.tsx
  src/app/pagamento/recarregar/boleto/page.tsx
  src/app/pagamento/recarregar/mastercard/page.tsx
  src/app/pagamento/recarregar/pix/code/page.tsx
  src/app/pagamento/recarregar/pix/page.tsx
  src/app/pagamento/saque/page.tsx
  src/components/Forms/FormRoot.tsx
  src/components/Forms/Input/index.tsx
  src/components/Forms/Type/FormInputButton.tsx
  src/components/Forms/Type/FormInputCPF.tsx
  src/components/Forms/Type/FormInputCard.tsx
  src/components/Forms/Type/FormInputDate.tsx
  src/components/Forms/Type/FormInputEmail.tsx
  src/components/Forms/Type/FormInputMonthYear.tsx
  src/components/Forms/Type/FormInputNumber.tsx
  src/components/Forms/Type/FormInputPhone.tsx
  src/components/Forms/Type/FormInputText.tsx
  src/components/Forms/index.tsx
  src/components/Payment/Form/Recharge/index.mastercard.tsx
  src/components/Payment/Form/Recharge/index.pix.tsx
  src/components/Payment/Form/Recharge/index.ticket.tsx
  src/components/Payment/Form/Withdraw/index.location.tsx
  src/components/Payment/Form/Withdraw/index.personal.tsx
  src/components/Payment/Form/Withdraw/index.transaction.tsx
  src/services/interfaces/notification.interface.ts
  src/services/notifications.service.ts
  src/stores/interfaces/filters.interface.ts
  yarn.lock
Labels: enhancement, Code Review

#63 [ Tiago Braga ] Forms - Refatoração do Componente pt.2
  src/app/pagamento/saque/page.tsx
  src/components/Forms/Dropzone/index.tsx
  src/components/Forms/FormButton.tsx
  src/components/Forms/FormDropdown.tsx
  src/components/Forms/FormDropzone.tsx
  src/components/Forms/Type/FormInputPostalCode.tsx
  src/components/Forms/index.tsx
  src/components/Icons/IconDropdownArrow.tsx
  src/components/Payment/Form/Withdraw/index.documents.tsx
  src/components/Payment/Form/Withdraw/index.location.tsx
  src/components/Payment/Form/Withdraw/index.transaction.tsx
  src/components/Payment/Form/Withdraw/index.tsx
  src/stores/interfaces/payment.interface.ts
Labels: enhancement, Code Review

#66 [ Tiago Braga ] Tweaks - Corrigindo Items em 'Segurança'
  src/Mock/notification.transaction.mock.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/usuario/configuracoes/page.tsx
  src/components/Forms/Input/Radio/FormInputRadioBlock.tsx
  src/components/Forms/options.ts
  src/components/Icons/IconGear.tsx
  src/components/Icons/IconLockedShield.tsx
  src/components/Icons/IconPaper.tsx
  src/components/Others/TransactionsTable/index.tsx
  src/components/Pages/PageSettings/PageSettingsInformation.tsx
  src/components/Pages/PageSettings/PageSettingsSecurity.tsx
  src/components/Pages/PageSettings/PageSettingsTransactions.tsx
  src/components/Pages/PageSettings/Transactions/PageSettingsTransactionsContent.tsx
  src/stores/components.store.ts
Labels: enhancement, Code Review

#67 [ Tiago Braga ] Tweaks - Finalizando Problemas do Header / Criando Nova Página para Perfil
  src/app/perfil/[id]/page.tsx
  src/app/perfil/page.tsx
  src/app/perfil/vendedor/[id]/page.tsx
  src/components/Layout/Header/LayoutHeaderDropdown.tsx
  src/components/Layout/Header/LayoutHeaderTop.tsx
Labels: enhancement, Code Review

#69 [ Gabriel Almeida ] Tweaks - Correção de typos 'any' do código #157
  .eslintrc.json
  src/app/pagamento/recarregar/[method]/page.tsx
  src/app/pagamento/saque/page.tsx
  src/app/usuario/configuracoes/page.tsx
  src/app/usuario/notificacoes/page.tsx
  src/assets/fallen.svg
  src/components/Forms/FormDropdown.tsx
  src/components/Forms/Input/FormInputCPF.tsx
  src/components/Forms/Input/FormInputCard.tsx
  src/components/Forms/Input/FormInputCheckbox.tsx
  src/components/Forms/Input/FormInputCurrency.tsx
  src/components/Forms/Input/FormInputDate.tsx
  src/components/Forms/Input/FormInputEmail.tsx
  src/components/Forms/Input/FormInputMonthYear.tsx
  src/components/Forms/Input/FormInputNumber.tsx
  src/components/Forms/Input/FormInputPhone.tsx
  src/components/Forms/Input/FormInputPostalCode.tsx
  src/components/Forms/Input/FormInputText.tsx
  src/components/Forms/Input/Radio/FormInputRadioBlock.tsx
  src/components/Forms/Input/Radio/FormInputRadioInline.tsx
  src/components/Icons/payment/IconPayPal.tsx
  src/components/Layout/Header/LayoutHeaderDropdown.tsx
  src/components/Layout/Header/LayoutHeaderTop.tsx
  src/components/Modal/ModalConnectInventory/ModalConnectInventoryForm.tsx
  src/components/Modal/ModalFilters/ModalFiltersPrice.tsx
  src/components/Modal/ModalNotification/ModalNotificationFilter.tsx
  src/components/Modal/ModalPayment/ModalPaymentAdd.tsx
  src/components/Modal/ModalPayment/ModalPaymentRetrieve/ModalPaymentRetrieveSelection.tsx
  src/components/Others/CardSkin/CardSkinInventory.tsx
  src/components/Others/ProfileInfo/index.tsx
  src/components/Pages/PagePayment/PagePaymentRecharge/PagePaymentRechargeMastercard.tsx
  src/components/Pages/PagePayment/PagePaymentRecharge/PagePaymentRechargePix.tsx
  src/components/Pages/PagePayment/PagePaymentRecharge/PagePaymentRechargeTicket.tsx
  src/components/Pages/PagePayment/PagePaymentWithdraw/PagePaymentWithdrawDocument.tsx
  src/components/Pages/PagePayment/PagePaymentWithdraw/PagePaymentWithdrawLocation.tsx
  src/components/Pages/PagePayment/PagePaymentWithdraw/PagePaymentWithdrawPersonal.tsx
  src/components/Pages/PagePayment/PagePaymentWithdraw/PagePaymentWithdrawTransaction.tsx
  src/interfaces/IInventoryDescription.ts
  src/interfaces/IInventorySkin.ts
  src/providers/Api.ts
  src/services/Configuracao.service.ts
  src/services/SkinService.ts
  src/services/notifications.service.ts
  src/services/wallet.service.ts
Labels: Code Review

#70 [ Gabriel Almeida ] Tweaks - Atualizando endpoints do axios para a nova api #161
  src/app/categorias/[skinName]/page.tsx
  src/app/home/page.tsx
  src/components/Modal/ModalFilters/ModalFiltersCategory.tsx
  src/components/Modal/ModalFilters/ModalFiltersMain.tsx
  src/components/Modal/ModalFilters/ModalFiltersPrice.tsx
  src/components/Others/SkinFilters/ContainerFilter/index.tsx
  src/components/Others/SkinFilters/index.tsx
  src/components/Others/Skins/AllSkins/index.tsx
  src/components/Skins/AllSkeletonSkins/index.tsx
  src/services/SkinService.ts
  yarn.lock
Labels: Code Review

#78 [ Gabriel Alemida ] Perfil - Refatoração da página perfil.
  src/app/perfil/[id]/page.tsx
  src/app/perfil/[userSteamId]/page.tsx
  src/app/perfil/page.tsx
  src/app/perfil/vendedor/[id]/page.tsx
Labels: Code Review

#84 [ Tiago Braga ] Inventário - Corrigindo Nome dos Cards do Inventário
  src/components/Layout/LayoutPagination.tsx
  src/components/Others/CardSkin/CardSkinContent.tsx
  src/components/Others/CardSkin/CardSkinInventory.tsx
Labels: Melhoria/Refatoração, Code Review, Prioridade: Baixa, Merge
